name: Lint

on: push

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install black
        run: python -m pip install --upgrade pip black
      - name: black
        run: black . --check

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install pytest code coverage
        run: python -m pip install --upgrade "pytest-cov~=4.0"
      - name: testcoverage
        run: python -m pytest -n auto --cov-report=term-missing --cov=test --cov=marshy --cov=marshy_config_default --cov-fail-under=100
